from __future__ import annotations

from pathlib import Path
from typing import Protocol, Self

from stratton_bot.domain.entities import (
    ActiveTesting,
    BookedSlotDetail,
    NdaRecordData,
    NotificationTarget,
    ReminderTarget,
    StatsSummary,
    SubmissionRecord,
    TimeSlot,
    UserProfile,
)


class UserRepository(Protocol):
    async def upsert(self, user_id: int, username: str | None, full_name: str | None, locale: str) -> None: ...
    async def get_by_id(self, user_id: int) -> UserProfile | None: ...
    async def set_status(self, user_id: int, status: str) -> None: ...
    async def increment_retry(self, user_id: int) -> None: ...
    async def list_all(self) -> list[UserProfile]: ...


class SlotRepository(Protocol):
    async def ensure_for_date(self, date_str: str, start_hour: int, end_hour: int) -> None: ...
    async def list_by_date(self, date_str: str) -> list[TimeSlot]: ...
    async def get_by_id(self, slot_id: int) -> TimeSlot | None: ...
    async def book(self, slot_id: int, user_id: int) -> bool: ...
    async def release(self, slot_id: int) -> None: ...
    async def list_booked_dates(self) -> list[dict[str, int | str]]: ...
    async def list_booked_details(self, date_str: str) -> list[BookedSlotDetail]: ...
    async def list_for_reminder(self, date_str: str, hour_str: str) -> list[ReminderTarget]: ...
    async def mark_reminded(self, slot_id: int) -> None: ...
    async def list_for_notification(self, date_str: str, hour_str: str) -> list[NotificationTarget]: ...
    async def mark_notified(self, slot_id: int) -> None: ...


class TestingRepository(Protocol):
    async def create(self, user_id: int, slot_id: int, task_variant: int) -> ActiveTesting: ...
    async def get_active_by_user(self, user_id: int) -> ActiveTesting | None: ...
    async def get_by_id(self, testing_id: int) -> ActiveTesting | None: ...
    async def set_status(self, testing_id: int, status: str) -> None: ...
    async def submit_active(self, user_id: int) -> None: ...
    async def list_open(self) -> list[ActiveTesting]: ...


class SubmissionRepository(Protocol):
    async def create(
        self,
        *,
        user_id: int,
        testing_id: int | None,
        file_id: str | None,
        file_type: str | None,
        link: str | None,
        file_size: int | None,
    ) -> SubmissionRecord: ...
    async def list_pending(self) -> list[SubmissionRecord]: ...
    async def get_by_id(self, submission_id: int) -> SubmissionRecord | None: ...
    async def review(self, submission_id: int, decision: str, reviewer_id: int) -> None: ...


class NdaRepository(Protocol):
    async def create(self, user_id: int) -> NdaRecordData: ...
    async def update(self, nda_id: int, fields: dict[str, str | None]) -> None: ...
    async def list_completed(self) -> list[NdaRecordData]: ...
    async def search(self, query: str) -> list[NdaRecordData]: ...


class StatsRepository(Protocol):
    async def get_summary(self) -> StatsSummary: ...


class UnitOfWork(Protocol):
    users: UserRepository
    slots: SlotRepository
    testings: TestingRepository
    submissions: SubmissionRepository
    ndas: NdaRepository
    stats: StatsRepository

    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def __call__(self) -> UnitOfWork: ...


class UserExporter(Protocol):
    def export(self, users: list[UserProfile], output_path: Path) -> Path: ...


class NDADocumentGenerator(Protocol):
    def generate(self, nda: NdaRecordData, output_path: Path) -> Path: ...
